In [11]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import sqlite3
from pymongo import MongoClient

file_to_load = "Arrivals_NonRes.csv"

# Read Purchasing File and store into Pandas data frame
base_data = pd.read_csv(file_to_load, encoding="UTF-8")
base_data

,COUNTRY,CODE,LATITUDE,LONGITUDE,TOURISM,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,AFGHANISTAN,AF,33.939110,67.709953,IN Arrivals - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,AFGHANISTAN,AF,33.939110,67.709953,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,36,89,147,165,167,179,121,87,69,19
2,AFGHANISTAN,AF,33.939110,67.709953,IN Travel - US$ Mn,..,..,..,..,..,...,8,36,75,85,102,138,109,79,49,2
3,AFGHANISTAN,AF,33.939110,67.709953,IN Passenger transport - US$ Mn,..,..,..,..,..,...,28,53,72,80,65,41,12,8,20,17
4,AFGHANISTAN,AF,33.939110,67.709953,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
5,AFGHANISTAN,AF,33.939110,67.709953,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,28,70,106,255,110,138,140,151,89,132
6,AFGHANISTAN,AF,33.939110,67.709953,OUT Travel - US$ Mn,..,..,..,..,..,...,26,68,103,246,105,132,137,147,79,118
7,AFGHANISTAN,AF,33.939110,67.709953,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,2,2,3,9,5,6,3,4,10,14
8,ALBANIA,AL,41.153332,20.168331,IN Arrivals - Thousands,345,351,142,206,397,...,"2,724","3,632","4,682","5,537","6,819","6,231","7,175","8,172","8,806","9,761"
9,ALBANIA,AL,41.153332,20.168331,IN Tourism expenditure in the country - US$ Mn,70,94,34,60,218,...,"1,849","2,012","1,778","1,832","1,624","1,670","1,848","1,613","1,820","2,049"
10,ALBANIA,AL,41.153332,20.168331,IN Travel - US$ Mn,65,77,27,54,211,...,"1,714","1,827","1,611","1,631","1,464","1,473","1,699","1,499","1,692","1,942"
11,ALBANIA,AL,41.153332,20.168331,IN Passenger transport - US$ Mn,5,17,7,6,7,...,135,185,167,201,160,197,149,114,128,107
12,ALBANIA,AL,41.153332,20.168331,OUT Departures - Thousands,..,..,..,..,..,...,"3,716","3,404","3,443","4,120","3,959","3,928","4,146","4,504","4,852","5,186"
13,ALBANIA,AL,41.153332,20.168331,OUT Tourism expenditure in other countries - U...,19,25,13,22,35,...,"1,644","1,691","1,452","1,676","1,374","1,567","1,689","1,310","1,338","1,472"
14,ALBANIA,AL,41.153332,20.168331,OUT Travel - US$ Mn,7,12,5,5,12,...,"1,555","1,584","1,360","1,564","1,284","1,479","1,590","1,237","1,262","1,432"
15,ALBANIA,AL,41.153332,20.168331,OUT Passenger transport - US$ Mn,12,13,8,17,23,...,89,107,92,112,90,88,99,73,76,40
16,ALGERIA,DZ,28.033886,1.659626,IN Arrivals - Thousands,520,605,635,678,749,...,"1,772","1,912","2,070","2,395","2,634","2,733","2,301","1,710","2,039","2,451"
17,ALGERIA,DZ,28.033886,1.659626,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,473,361,324,300,295,326,316,347,246,172
18,ALGERIA,DZ,28.033886,1.659626,IN Travel - US$ Mn,32,45,28,74,80,...,323,246,220,209,217,250,258,311,209,141
19,ALGERIA,DZ,28.033886,1.659626,IN Passenger transport - US$ Mn,..,..,..,..,..,...,150,115,104,91,78,76,58,36,37,31
20,ALGERIA,DZ,28.033886,1.659626,OUT Departures - Thousands,"1,090",874,827,879,903,...,"1,539","1,677","1,757","1,715","1,911","2,136","2,839","3,638","4,530","5,058"
21,ALGERIA,DZ,28.033886,1.659626,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,613,574,716,595,598,531,679,762,556,632
22,ALGERIA,DZ,28.033886,1.659626,OUT Travel - US$ Mn,186,188,144,269,251,...,468,456,601,527,529,471,608,685,474,580
23,ALGERIA,DZ,28.033886,1.659626,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,145,118,115,68,69,60,71,77,82,52
24,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Arrivals - Thousands,34,35,26,36,41,...,24.3,23.5,23.1,22.6,22.6,20.8,21.6,20.3,20.1,20
25,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
26,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,22,22
27,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
28,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
29,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,VIET NAM,VN,14.058324,108.277199,IN Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1727,VIET NAM,VN,14.058324,108.277199,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1728,VIET NAM,VN,14.058324,108.277199,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1729,VIET NAM,VN,14.058324,108.277199,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,"1,300","1,100","1,470","1,710","1,856","2,050","2,650","3,595","4,500","5,040"
1730,VIET NAM,VN,14.058324,108.277199,OUT Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1731,VIET NAM,VN,14.058324,108.277199,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1732,YEMEN,YE,15.552727,48.516388,IN Arrivals - Thousands,61,74,80,88,58,...,"1,023","1,028","1,025",829,874,990,"1,018",367,..,..
1733,YEMEN,YE,15.552727,48.516388,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,"1,291",910,"1,005","1,097","1,199",116,116,..
1734,YEMEN,YE,15.552727,48.516388,IN Travel - US$ Mn,50,55,70,84,61,...,886,899,"1,161",780,848,940,"1,026",100,100,..
1735,YEMEN,YE,15.552727,48.516388,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,130,130,157,157,173,16,16,..
1736,YEMEN,YE,15.552727,48.516388,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1737,YEMEN,YE,15.552727,48.516388,OUT Tourism expenditure in other countries - U...,..,..,..,160,164,...,246,277,252,258,148,161,158,79,56,..
1738,YEMEN,YE,15.552727,48.516388,OUT Travel - US$ Mn,76,78,124,130,136,...,183,214,183,182,73,86,77,72,49,..
1739,YEMEN,YE,15.552727,48.516388,OUT Passenger transport - US$ Mn,..,..,..,30,28,...,63,63,69,76,75,75,81,7,7,..
1740,ZAMBIA,ZM,-13.133897,27.849332,IN Arrivals - Thousands,163,264,341,362,404,...,812,710,815,920,859,915,947,932,956,"1,083"
1741,ZAMBIA,ZM,-13.133897,27.849332,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1742,ZAMBIA,ZM,-13.133897,27.849332,IN Travel - US$ Mn,..,..,29,40,53,...,542,474,492,555,518,552,642,660,683,653
1743,ZAMBIA,ZM,-13.133897,27.849332,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1744,ZAMBIA,ZM,-13.133897,27.849332,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1745,ZAMBIA,ZM,-13.133897,27.849332,OUT Tourism expenditure in other countries - U...,..,..,83,81,100,...,164,143,167,223,303,357,378,400,423,410
1746,ZAMBIA,ZM,-13.133897,27.849332,OUT Travel - US$ Mn,..,..,26,24,43,...,118,96,105,111,165,210,222,234,247,223
1747,ZAMBIA,ZM,-13.133897,27.849332,OUT Passenger transport - US$ Mn,..,..,57,57,57,...,46,47,62,112,138,147,156,166,176,187
1748,ZIMBABWE,ZW,-19.015438,29.154857,IN Arrivals - Thousands,"2,779","3,174","2,617","4,076","4,351",...,"1,956","2,017","2,239","2,423","1,794","1,833","1,880","2,057","2,168","2,423"
1749,ZIMBABWE,ZW,-19.015438,29.154857,IN Tourism expenditure in the country - US$ Mn,145,232,205,158,202,...,294,129,135,164,174,183,186,191,194,158
1750,ZIMBABWE,ZW,-19.015438,29.154857,IN Travel - US$ Mn,..,..,..,..,..,...,..,118,124,152,161,170,172,175,177,149
1751,ZIMBABWE,ZW,-19.015438,29.154857,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,11,11,12,13,13,14,16,17,9
1752,ZIMBABWE,ZW,-19.015438,29.154857,OUT Departures - Thousands,256,69,123,213,331,...,593,631,650,693,720,"2,946","3,182","3,393","3,192","2,768"
1753,ZIMBABWE,ZW,-19.015438,29.154857,OUT Tourism expenditure in other countries - U...,106,118,120,131,..,...,..,167,203,317,387,441,451,557,406,338
1754,ZIMBABWE,ZW,-19.015438,29.154857,OUT Travel - US$ Mn,..,..,..,..,..,...,..,110,131,228,272,337,342,476,327,315
1755,ZIMBABWE,ZW,-19.015438,29.154857,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,..,57,72,89,115,104,109,81,79,23

In [2]:
#base_data.replace({'..': np.nan})
base_data.replace({'..': 0})

,COUNTRY,CODE,LATITUDE,LONGITUDE,TOURISM,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,AFGHANISTAN,AF,33.939110,67.709953,IN Arrivals - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AFGHANISTAN,AF,33.939110,67.709953,IN Tourism expenditure in the country - US$ Mn,0,0,0,0,0,...,36,89,147,165,167,179,121,87,69,19
2,AFGHANISTAN,AF,33.939110,67.709953,IN Travel - US$ Mn,0,0,0,0,0,...,8,36,75,85,102,138,109,79,49,2
3,AFGHANISTAN,AF,33.939110,67.709953,IN Passenger transport - US$ Mn,0,0,0,0,0,...,28,53,72,80,65,41,12,8,20,17
4,AFGHANISTAN,AF,33.939110,67.709953,OUT Departures - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,AFGHANISTAN,AF,33.939110,67.709953,OUT Tourism expenditure in other countries - U...,0,0,0,0,0,...,28,70,106,255,110,138,140,151,89,132
6,AFGHANISTAN,AF,33.939110,67.709953,OUT Travel - US$ Mn,0,0,0,0,0,...,26,68,103,246,105,132,137,147,79,118
7,AFGHANISTAN,AF,33.939110,67.709953,OUT Passenger transport - US$ Mn,0,0,0,0,0,...,2,2,3,9,5,6,3,4,10,14
8,ALBANIA,AL,41.153332,20.168331,IN Arrivals - Thousands,345,351,142,206,397,...,"2,724","3,632","4,682","5,537","6,819","6,231","7,175","8,172","8,806","9,761"
9,ALBANIA,AL,41.153332,20.168331,IN Tourism expenditure in the country - US$ Mn,70,94,34,60,218,...,"1,849","2,012","1,778","1,832","1,624","1,670","1,848","1,613","1,820","2,049"
10,ALBANIA,AL,41.153332,20.168331,IN Travel - US$ Mn,65,77,27,54,211,...,"1,714","1,827","1,611","1,631","1,464","1,473","1,699","1,499","1,692","1,942"
11,ALBANIA,AL,41.153332,20.168331,IN Passenger transport - US$ Mn,5,17,7,6,7,...,135,185,167,201,160,197,149,114,128,107
12,ALBANIA,AL,41.153332,20.168331,OUT Departures - Thousands,0,0,0,0,0,...,"3,716","3,404","3,443","4,120","3,959","3,928","4,146","4,504","4,852","5,186"
13,ALBANIA,AL,41.153332,20.168331,OUT Tourism expenditure in other countries - U...,19,25,13,22,35,...,"1,644","1,691","1,452","1,676","1,374","1,567","1,689","1,310","1,338","1,472"
14,ALBANIA,AL,41.153332,20.168331,OUT Travel - US$ Mn,7,12,5,5,12,...,"1,555","1,584","1,360","1,564","1,284","1,479","1,590","1,237","1,262","1,432"
15,ALBANIA,AL,41.153332,20.168331,OUT Passenger transport - US$ Mn,12,13,8,17,23,...,89,107,92,112,90,88,99,73,76,40
16,ALGERIA,DZ,28.033886,1.659626,IN Arrivals - Thousands,520,605,635,678,749,...,"1,772","1,912","2,070","2,395","2,634","2,733","2,301","1,710","2,039","2,451"
17,ALGERIA,DZ,28.033886,1.659626,IN Tourism expenditure in the country - US$ Mn,0,0,0,0,0,...,473,361,324,300,295,326,316,347,246,172
18,ALGERIA,DZ,28.033886,1.659626,IN Travel - US$ Mn,32,45,28,74,80,...,323,246,220,209,217,250,258,311,209,141
19,ALGERIA,DZ,28.033886,1.659626,IN Passenger transport - US$ Mn,0,0,0,0,0,...,150,115,104,91,78,76,58,36,37,31
20,ALGERIA,DZ,28.033886,1.659626,OUT Departures - Thousands,"1,090",874,827,879,903,...,"1,539","1,677","1,757","1,715","1,911","2,136","2,839","3,638","4,530","5,058"
21,ALGERIA,DZ,28.033886,1.659626,OUT Tourism expenditure in other countries - U...,0,0,0,0,0,...,613,574,716,595,598,531,679,762,556,632
22,ALGERIA,DZ,28.033886,1.659626,OUT Travel - US$ Mn,186,188,144,269,251,...,468,456,601,527,529,471,608,685,474,580
23,ALGERIA,DZ,28.033886,1.659626,OUT Passenger transport - US$ Mn,0,0,0,0,0,...,145,118,115,68,69,60,71,77,82,52
24,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Arrivals - Thousands,34,35,26,36,41,...,24.3,23.5,23.1,22.6,22.6,20.8,21.6,20.3,20.1,20
25,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Tourism expenditure in the country - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Travel - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,22,22
27,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Passenger transport - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Departures - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Tourism expenditure in other countries - U...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,VIET NAM,VN,14.058324,108.277199,IN Travel - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1727,VIET NAM,VN,14.058324,108.277199,IN Passenger transport - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1728,VIET NAM,VN,14.058324,108.277199,OUT Departures - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1729,VIET NAM,VN,14.058324,108.277199,OUT Tourism expenditure in other countries - U...,0,0,0,0,0,...,"1,300","1,100","1,470","1,710","1,856","2,050","2,650","3,595","4,500","5,040"
1730,VIET NAM,VN,14.058324,108.277199,OUT Travel - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1731,VIET NAM,VN,14.058324,108.277199,OUT Passenger transport - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1732,YEMEN,YE,15.552727,48.516388,IN Arrivals - Thousands,61,74,80,88,58,...,"1,023","1,028","1,025",829,874,990,"1,018",367,0,0
1733,YEMEN,YE,15.552727,48.516388,IN Tourism expenditure in the country - US$ Mn,0,0,0,0,0,...,0,0,"1,291",910,"1,005","1,097","1,199",116,116,0
1734,YEMEN,YE,15.552727,48.516388,IN Travel - US$ Mn,50,55,70,84,61,...,886,899,"1,161",780,848,940,"1,026",100,100,0
1735,YEMEN,YE,15.552727,48.516388,IN Passenger transport - US$ Mn,0,0,0,0,0,...,0,0,130,130,157,157,173,16,16,0
1736,YEMEN,YE,15.552727,48.516388,OUT Departures - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1737,YEMEN,YE,15.552727,48.516388,OUT Tourism expenditure in other countries - U...,0,0,0,160,164,...,246,277,252,258,148,161,158,79,56,0
1738,YEMEN,YE,15.552727,48.516388,OUT Travel - US$ Mn,76,78,124,130,136,...,183,214,183,182,73,86,77,72,49,0
1739,YEMEN,YE,15.552727,48.516388,OUT Passenger transport - US$ Mn,0,0,0,30,28,...,63,63,69,76,75,75,81,7,7,0
1740,ZAMBIA,ZM,-13.133897,27.849332,IN Arrivals - Thousands,163,264,341,362,404,...,812,710,815,920,859,915,947,932,956,"1,083"
1741,ZAMBIA,ZM,-13.133897,27.849332,IN Tourism expenditure in the country - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1742,ZAMBIA,ZM,-13.133897,27.849332,IN Travel - US$ Mn,0,0,29,40,53,...,542,474,492,555,518,552,642,660,683,653
1743,ZAMBIA,ZM,-13.133897,27.849332,IN Passenger transport - US$ Mn,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1744,ZAMBIA,ZM,-13.133897,27.849332,OUT Departures - Thousands,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1745,ZAMBIA,ZM,-13.133897,27.849332,OUT Tourism expenditure in other countries - U...,0,0,83,81,100,...,164,143,167,223,303,357,378,400,423,410
1746,ZAMBIA,ZM,-13.133897,27.849332,OUT Travel - US$ Mn,0,0,26,24,43,...,118,96,105,111,165,210,222,234,247,223
1747,ZAMBIA,ZM,-13.133897,27.849332,OUT Passenger transport - US$ Mn,0,0,57,57,57,...,46,47,62,112,138,147,156,166,176,187
1748,ZIMBABWE,ZW,-19.015438,29.154857,IN Arrivals - Thousands,"2,779","3,174","2,617","4,076","4,351",...,"1,956","2,017","2,239","2,423","1,794","1,833","1,880","2,057","2,168","2,423"
1749,ZIMBABWE,ZW,-19.015438,29.154857,IN Tourism expenditure in the country - US$ Mn,145,232,205,158,202,...,294,129,135,164,174,183,186,191,194,158
1750,ZIMBABWE,ZW,-19.015438,29.154857,IN Travel - US$ Mn,0,0,0,0,0,...,0,118,124,152,161,170,172,175,177,149
1751,ZIMBABWE,ZW,-19.015438,29.154857,IN Passenger transport - US$ Mn,0,0,0,0,0,...,0,11,11,12,13,13,14,16,17,9
1752,ZIMBABWE,ZW,-19.015438,29.154857,OUT Departures - Thousands,256,69,123,213,331,...,593,631,650,693,720,"2,946","3,182","3,393","3,192","2,768"
1753,ZIMBABWE,ZW,-19.015438,29.154857,OUT Tourism expenditure in other countries - U...,106,118,120,131,0,...,0,167,203,317,387,441,451,557,406,338
1754,ZIMBABWE,ZW,-19.015438,29.154857,OUT Travel - US$ Mn,0,0,0,0,0,...,0,110,131,228,272,337,342,476,327,315
1755,ZIMBABWE,ZW,-19.015438,29.154857,OUT Passenger transport - US$ Mn,0,0,0,0,0,...,0,57,72,89,115,104,109,81,79,23

In [3]:
DB_Name = 'Tourism_DB'
engine = create_engine(f'sqlite:///{DB_Name}')

In [7]:
engine.execute('CREATE TABLE "Tourism" ('
               'Country VARCHAR NOT NULL,'
               'Code VARCHAR,'
               'Latitude FLOAT NOT NULL,'
               'Longitude FLOAT NOT NULL,'
               'Tourism VARCHAR NOT NULL,'
               '`1995` FLOAT NOT NULL,'
               '`1996` FLOAT NOT NULL,'
               '`1997` FLOAT NOT NULL,'
               '`1998` FLOAT NOT NULL,'
               '`1999` FLOAT NOT NULL,'
               '`2000` FLOAT NOT NULL,'
               '`2001` FLOAT NOT NULL,'
               '`2002` FLOAT NOT NULL,'
               '`2003` FLOAT NOT NULL,'
               '`2004` FLOAT NOT NULL,'
               '`2005` FLOAT NOT NULL,'
               '`2006` FLOAT NOT NULL,'
               '`2007` FLOAT NOT NULL,'
               '`2008` FLOAT NOT NULL,'
               '`2009` FLOAT NOT NULL,'
               '`2010` FLOAT NOT NULL,'
               '`2011` FLOAT NOT NULL,'
               '`2012` FLOAT NOT NULL,'
               '`2013` FLOAT NOT NULL,'
               '`2014` FLOAT NOT NULL,'
               '`2015` FLOAT NOT NULL,'
               '`2016` FLOAT NOT NULL,'
               '`2017` FLOAT NOT NULL);')

In [8]:
base_data.to_sql(name='Tourism', con=engine, if_exists='append', index=False)

In [9]:
# Connecting to the Database
cnx = sqlite3.connect('Tourism_DB')

# Converting a Table in the Database into a Pandas DataFrame
df = pd.read_sql_query("SELECT * FROM Tourism", cnx)

In [10]:
df

,Country,Code,Latitude,Longitude,Tourism,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,AFGHANISTAN,AF,33.939110,67.709953,IN Arrivals - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,AFGHANISTAN,AF,33.939110,67.709953,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,36,89,147,165,167,179,121,87,69,19
2,AFGHANISTAN,AF,33.939110,67.709953,IN Travel - US$ Mn,..,..,..,..,..,...,8,36,75,85,102,138,109,79,49,2
3,AFGHANISTAN,AF,33.939110,67.709953,IN Passenger transport - US$ Mn,..,..,..,..,..,...,28,53,72,80,65,41,12,8,20,17
4,AFGHANISTAN,AF,33.939110,67.709953,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
5,AFGHANISTAN,AF,33.939110,67.709953,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,28,70,106,255,110,138,140,151,89,132
6,AFGHANISTAN,AF,33.939110,67.709953,OUT Travel - US$ Mn,..,..,..,..,..,...,26,68,103,246,105,132,137,147,79,118
7,AFGHANISTAN,AF,33.939110,67.709953,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,2,2,3,9,5,6,3,4,10,14
8,ALBANIA,AL,41.153332,20.168331,IN Arrivals - Thousands,345,351,142,206,397,...,"2,724","3,632","4,682","5,537","6,819","6,231","7,175","8,172","8,806","9,761"
9,ALBANIA,AL,41.153332,20.168331,IN Tourism expenditure in the country - US$ Mn,70,94,34,60,218,...,"1,849","2,012","1,778","1,832","1,624","1,670","1,848","1,613","1,820","2,049"
10,ALBANIA,AL,41.153332,20.168331,IN Travel - US$ Mn,65,77,27,54,211,...,"1,714","1,827","1,611","1,631","1,464","1,473","1,699","1,499","1,692","1,942"
11,ALBANIA,AL,41.153332,20.168331,IN Passenger transport - US$ Mn,5,17,7,6,7,...,135,185,167,201,160,197,149,114,128,107
12,ALBANIA,AL,41.153332,20.168331,OUT Departures - Thousands,..,..,..,..,..,...,"3,716","3,404","3,443","4,120","3,959","3,928","4,146","4,504","4,852","5,186"
13,ALBANIA,AL,41.153332,20.168331,OUT Tourism expenditure in other countries - U...,19,25,13,22,35,...,"1,644","1,691","1,452","1,676","1,374","1,567","1,689","1,310","1,338","1,472"
14,ALBANIA,AL,41.153332,20.168331,OUT Travel - US$ Mn,7,12,5,5,12,...,"1,555","1,584","1,360","1,564","1,284","1,479","1,590","1,237","1,262","1,432"
15,ALBANIA,AL,41.153332,20.168331,OUT Passenger transport - US$ Mn,12,13,8,17,23,...,89,107,92,112,90,88,99,73,76,40
16,ALGERIA,DZ,28.033886,1.659626,IN Arrivals - Thousands,520,605,635,678,749,...,"1,772","1,912","2,070","2,395","2,634","2,733","2,301","1,710","2,039","2,451"
17,ALGERIA,DZ,28.033886,1.659626,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,473,361,324,300,295,326,316,347,246,172
18,ALGERIA,DZ,28.033886,1.659626,IN Travel - US$ Mn,32,45,28,74,80,...,323,246,220,209,217,250,258,311,209,141
19,ALGERIA,DZ,28.033886,1.659626,IN Passenger transport - US$ Mn,..,..,..,..,..,...,150,115,104,91,78,76,58,36,37,31
20,ALGERIA,DZ,28.033886,1.659626,OUT Departures - Thousands,"1,090",874,827,879,903,...,"1,539","1,677","1,757","1,715","1,911","2,136","2,839","3,638","4,530","5,058"
21,ALGERIA,DZ,28.033886,1.659626,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,613,574,716,595,598,531,679,762,556,632
22,ALGERIA,DZ,28.033886,1.659626,OUT Travel - US$ Mn,186,188,144,269,251,...,468,456,601,527,529,471,608,685,474,580
23,ALGERIA,DZ,28.033886,1.659626,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,145,118,115,68,69,60,71,77,82,52
24,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Arrivals - Thousands,34,35,26,36,41,...,24.3,23.5,23.1,22.6,22.6,20.8,21.6,20.3,20.1,20
25,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
26,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,22,22
27,AMERICAN SAMOA,AS,-14.270972,-170.132217,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
28,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
29,AMERICAN SAMOA,AS,-14.270972,-170.132217,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,VIET NAM,VN,14.058324,108.277199,IN Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1727,VIET NAM,VN,14.058324,108.277199,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1728,VIET NAM,VN,14.058324,108.277199,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1729,VIET NAM,VN,14.058324,108.277199,OUT Tourism expenditure in other countries - U...,..,..,..,..,..,...,"1,300","1,100","1,470","1,710","1,856","2,050","2,650","3,595","4,500","5,040"
1730,VIET NAM,VN,14.058324,108.277199,OUT Travel - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1731,VIET NAM,VN,14.058324,108.277199,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1732,YEMEN,YE,15.552727,48.516388,IN Arrivals - Thousands,61,74,80,88,58,...,"1,023","1,028","1,025",829,874,990,"1,018",367,..,..
1733,YEMEN,YE,15.552727,48.516388,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,"1,291",910,"1,005","1,097","1,199",116,116,..
1734,YEMEN,YE,15.552727,48.516388,IN Travel - US$ Mn,50,55,70,84,61,...,886,899,"1,161",780,848,940,"1,026",100,100,..
1735,YEMEN,YE,15.552727,48.516388,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,130,130,157,157,173,16,16,..
1736,YEMEN,YE,15.552727,48.516388,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1737,YEMEN,YE,15.552727,48.516388,OUT Tourism expenditure in other countries - U...,..,..,..,160,164,...,246,277,252,258,148,161,158,79,56,..
1738,YEMEN,YE,15.552727,48.516388,OUT Travel - US$ Mn,76,78,124,130,136,...,183,214,183,182,73,86,77,72,49,..
1739,YEMEN,YE,15.552727,48.516388,OUT Passenger transport - US$ Mn,..,..,..,30,28,...,63,63,69,76,75,75,81,7,7,..
1740,ZAMBIA,ZM,-13.133897,27.849332,IN Arrivals - Thousands,163,264,341,362,404,...,812,710,815,920,859,915,947,932,956,"1,083"
1741,ZAMBIA,ZM,-13.133897,27.849332,IN Tourism expenditure in the country - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1742,ZAMBIA,ZM,-13.133897,27.849332,IN Travel - US$ Mn,..,..,29,40,53,...,542,474,492,555,518,552,642,660,683,653
1743,ZAMBIA,ZM,-13.133897,27.849332,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1744,ZAMBIA,ZM,-13.133897,27.849332,OUT Departures - Thousands,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1745,ZAMBIA,ZM,-13.133897,27.849332,OUT Tourism expenditure in other countries - U...,..,..,83,81,100,...,164,143,167,223,303,357,378,400,423,410
1746,ZAMBIA,ZM,-13.133897,27.849332,OUT Travel - US$ Mn,..,..,26,24,43,...,118,96,105,111,165,210,222,234,247,223
1747,ZAMBIA,ZM,-13.133897,27.849332,OUT Passenger transport - US$ Mn,..,..,57,57,57,...,46,47,62,112,138,147,156,166,176,187
1748,ZIMBABWE,ZW,-19.015438,29.154857,IN Arrivals - Thousands,"2,779","3,174","2,617","4,076","4,351",...,"1,956","2,017","2,239","2,423","1,794","1,833","1,880","2,057","2,168","2,423"
1749,ZIMBABWE,ZW,-19.015438,29.154857,IN Tourism expenditure in the country - US$ Mn,145,232,205,158,202,...,294,129,135,164,174,183,186,191,194,158
1750,ZIMBABWE,ZW,-19.015438,29.154857,IN Travel - US$ Mn,..,..,..,..,..,...,..,118,124,152,161,170,172,175,177,149
1751,ZIMBABWE,ZW,-19.015438,29.154857,IN Passenger transport - US$ Mn,..,..,..,..,..,...,..,11,11,12,13,13,14,16,17,9
1752,ZIMBABWE,ZW,-19.015438,29.154857,OUT Departures - Thousands,256,69,123,213,331,...,593,631,650,693,720,"2,946","3,182","3,393","3,192","2,768"
1753,ZIMBABWE,ZW,-19.015438,29.154857,OUT Tourism expenditure in other countries - U...,106,118,120,131,..,...,..,167,203,317,387,441,451,557,406,338
1754,ZIMBABWE,ZW,-19.015438,29.154857,OUT Travel - US$ Mn,..,..,..,..,..,...,..,110,131,228,272,337,342,476,327,315
1755,ZIMBABWE,ZW,-19.015438,29.154857,OUT Passenger transport - US$ Mn,..,..,..,..,..,...,..,57,72,89,115,104,109,81,79,23